version: "3.8"
services:
  nest:
    container_name: nest
    build: .
    tty: true
    ports:
      - "3000:3000"
    volumes:
      - type: bind
        source: .
        target: /api
    depends_on:
      - mysql
  mysql:
    container_name: mysql
    image: mysql/mysql-server:5.7
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: develop
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
    volumes:
      # 永続化するときにマウントするdir
      - nestdb:/var/lib/mysql
volumes:
  nestdb: